### ISSUE TITLE
current preset ( general ) is not lighted as active after using crescendo pedal

### ISSUE THREAD

**Issue by krgrwrg** [GrandOrgue/grandorgue#1299] opened 2022-12-04 19:32 UTC
Version : 3.9.1

Problem:
* is little bit confusing - i don't know which piston is activated
* especially when i assigned led buttons on midi controller to general pistons, after using crescendo pedal all leds are off.

Link to video : 
https://drive.google.com/file/d/1jAfXeCJ2ajlcwsm24CzZ2T9lLJmjRf3h/view?usp=sharing

This problem was reported in 1209 but is still not fixed properly.
Second problem ( when in switch between presets ( generals ) crescendo is ignored, but when i move it up or down, sound is changed. ) is fixed.

In version 3.9.2 general pistons don't recieve On States on my midi controller ( issue 1298 )

**Comment by oleg68** [comment] 2022-12-05 08:12
You have to switch the `Override` crescendo mode off for staying with the old position of generals: open Panel->Crescendo Pedal and disable `Override`.

In the override mode the new combination is taken from crescendo rather from general, so the old general position is forgotten. It is intended behavior.

**Comment by oleg68** [comment] 2022-12-05 09:31
@krgrwrg There is [an intermediate build](https://github.com/GrandOrgue/grandorgue/actions/runs/3618413333) with #1291 having been fixed.

Could you test this build with `Override` switched off? If everything OK, please close this issue. If some problems with generals+crescendo still exist, please describe them here.

**Comment by krgrwrg** [comment] 2022-12-05 22:43
> @krgrwrg There is [an intermediate build](https://github.com/GrandOrgue/grandorgue/actions/runs/3618413333) with #1291 having been fixed. 
> Could you test this build with the `Override` switched off? If everything OK, please close this issue. If some problems with generals+crescendo still exist, please describe them here.

Current preset ( general ) is not lighted as active ( #1298 ) - is fixed
My launchpad ( midi controller ) buttons are lighted as before.

But problem with crescendo pedal is still present. Override mode is off.
If i move crescendo pedal into zero position, general is not selected anymore.
Neighter in midi device ( launchpad ), nor in gui ( generals panel ).
Pistons are in previous position, but selected general is forgotten.

**Closed** 2022-12-09 16:05 UTC
