### ISSUE TITLE
Help and settings dialog problems

### ISSUE THREAD

**Issue by paolo2504** [GrandOrgue/grandorgue#1066] opened 2022-03-03 19:00 UTC
i tested latest r3631 under linux (raspbian) and WIndows 10 and found several issues.
linux: 
help dialog opens but Settings dialog looses focus and cannot be anymore selectable.
In addition, if the minimize button in the Help modal dialog is selected, then it disappears and cannot be reopened anymore (even if it can be seen in the top app bar). As a result, as both Settings, Help and GO windows/dialogs are no more focused they all cannot be closed and it is necessary to kill GO process from terminal.
A less important issue is that Help dialog on first open is 0-size and appears as a small vertical bar (look at last screen recording).

Windows:
more or less the same issues apart there is no need to kill process. When opening Help, its dialog stays always over the Settings dialog: this is not good in Windows as it should get fore and back as the two dialogs take focus (see the screencam on Treesize that is a small tool i ran just for example). And again, if the minimize button is choosen then it doesnt appear anymore, even pushing again the Help button. No Help is later on available even from Menu. The only way to reset situation is to close and restart GO.

Pls look at the screen captures below.

https://user-images.githubusercontent.com/50132661/156633497-2e2ccb01-96e0-4ceb-a8ea-73b89fb0ca99.mp4

https://user-images.githubusercontent.com/50132661/156633676-944fb7f9-a297-49c2-8b54-765e684b197f.mp4

https://user-images.githubusercontent.com/50132661/156633719-d291543e-5151-4ea8-a8a1-78ec391cca71.mp4

https://user-images.githubusercontent.com/50132661/156643002-5c9ce9b0-dbe2-47c0-b952-6881d5d5db1b.mp4

https://user-images.githubusercontent.com/50132661/156644170-071babea-0b0b-469b-99b0-3b5909d21e6e.mp4

**Comment by ahall41** [comment] 2022-03-04 10:32
I found when building from the latest Git repository that minimise/maximise and close are missing from Help, but this is OK with the 3.6.2-1 branch. Help also always stays on top, but I can close with Alt+F4. I'm running Ubuntu 20.04.3 LTS and 18.04.6 LTS.

**Comment by oleg68** [comment] 2022-04-04 19:51
@paolo2504 I've just tested GrandOrgue 3.6.4-1 on Raspbian 32-bit. I cann't reproduce the problem:

1. When I click on `Help`, the help window appears with a reasonable size.
2. The minimize and maximize buttons are greyed (disabled), so it is impossible to get it out.
3. The settings window is not selectable while the help window is open, but it is a desirable behavior.

Let's check the version of wxWidgets installed on your raspberry box:

```
pi@raspberrypi:~ $ apt list --installed | grep "wx"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libwxbase3.0-0v5/stable,now 3.0.5.1+dfsg-2 armhf [installed,automatic]
libwxgtk3.0-gtk3-0v5/stable,now 3.0.5.1+dfsg-2 armhf [installed,automatic]
```

**Comment by paolo2504** [comment] 2022-04-05 15:09
Oleg,
i get as follows and i confirm errors descibed with screen recorder...
Anyway it is not important with raspberry: it was just to notice to you that on Windows and raspbian too i am getting 
the same issue..
regards.

pi@raspberrypi:~ $ apt list --installed | grep "wx"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libwxbase3.0-0v5/oldstable,now 3.0.4+dfsg-8 armhf [installato, automatico]
libwxgtk3.0-gtk3-0v5/oldstable,now 3.0.4+dfsg-8 armhf [installato, automatico]

**Comment by oleg68** [comment] 2022-04-05 17:34
@paolo2504 
Seems the reason is the libraries are too old. Could you try to update libwxbase3.0-0v5 and libwxgtk3.0-gtk3-0v5 to the 3.0.5?

**Comment by paolo2504** [comment] 2022-04-05 18:41
Well… I’ve recently redo sd  card with raspberry os 32 bit legacy. I already did sudo apr update and full upgrade. 
today I reinstalled GO (that I never use on raspberry) only to be able to reply to your kind request. 
I don’t know why sudo update doesn’t update those libraries but on this actual sd I don’t want to make modifications other than standard update/upgrade so if u like I can use another sd as soon as I can. 

anycase, what is important imho is that also windows 10 shows the same issue. 
For me is not fatal: just don’t use Help from Settings tab !!

**Comment by paolo2504** [comment] 2022-04-06 12:45
ok. using another sd i made as follows. afaik, libraries were not updated... and issue is the same. Maybe i have to use another repository ?..

Anyway, i would be more interested on fixing issue in Windows..

regards.
paolo





pi@raspberrypi:~ $ apt list --installed | grep "wx"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

pi@raspberrypi:~ $ apt list --installed | grep "wx"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libwxbase3.0-0v5/oldstable,now 3.0.4+dfsg-8 armhf [installato, automatico]
libwxgtk3.0-gtk3-0v5/oldstable,now 3.0.4+dfsg-8 armhf [installato, automatico]


pi@raspberrypi:~ $ sudo apt install -y libwxbase3.0-dev
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
I seguenti pacchetti aggiuntivi saranno inoltre installati:
  wx3.0-headers
Pacchetti suggeriti:
  wx3.0-doc gettext
I seguenti pacchetti NUOVI saranno installati:
  libwxbase3.0-dev wx3.0-headers
0 aggiornati, 2 installati, 0 da rimuovere e 0 non aggiornati.
È necessario scaricare 1.267 kB di archivi.
Dopo quest'operazione, verranno occupati 7.112 kB di spazio su disco.
Scaricamento di:1 http://raspbian.mirror.garr.it/mirrors/raspbian/raspbian buster/main armhf wx3.0-headers all 3.0.4+dfsg-8 [1.128 kB]
Scaricamento di:2 http://raspbian.mirror.garr.it/mirrors/raspbian/raspbian buster/main armhf libwxbase3.0-dev armhf 3.0.4+dfsg-8 [138 kB]
Recuperati 1.267 kB in 2s (683 kB/s)      
Selezionato il pacchetto wx3.0-headers non precedentemente selezionato.
(Lettura del database... 189258 file e directory attualmente installati.)
Preparativi per estrarre .../wx3.0-headers_3.0.4+dfsg-8_all.deb...
Estrazione di wx3.0-headers (3.0.4+dfsg-8)...
Selezionato il pacchetto libwxbase3.0-dev:armhf non precedentemente selezionato.
Preparativi per estrarre .../libwxbase3.0-dev_3.0.4+dfsg-8_armhf.deb...
Estrazione di libwxbase3.0-dev:armhf (3.0.4+dfsg-8)...
Configurazione di wx3.0-headers (3.0.4+dfsg-8)...
Configurazione di libwxbase3.0-dev:armhf (3.0.4+dfsg-8)...
update-alternatives: viene usato /usr/lib/arm-linux-gnueabihf/wx/config/base-unicode-3.0 per fornire /usr/bin/wx-config (wx-config) in modalità automatica


pi@raspberrypi:~ $ sudo apt install -y libwxgtk3.0-dev
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
I seguenti pacchetti aggiuntivi saranno inoltre installati:
  libgl-dev libgl1-mesa-dev libglu1-mesa-dev libglx-dev libwxgtk3.0-0v5
  wx-common
Pacchetti suggeriti:
  wx3.0-doc gettext
I seguenti pacchetti NUOVI saranno installati:
  libgl-dev libgl1-mesa-dev libglu1-mesa-dev libglx-dev libwxgtk3.0-0v5
  libwxgtk3.0-dev wx-common
0 aggiornati, 7 installati, 0 da rimuovere e 0 non aggiornati.
È necessario scaricare 4.199 kB di archivi.
Dopo quest'operazione, verranno occupati 15,9 MB di spazio su disco.
Scaricamento di:1 http://archive.raspberrypi.org/debian buster/main armhf libglx-dev armhf 1.3.0-7~bpo10+1 [16,4 kB]
Scaricamento di:2 http://archive.raspberrypi.org/debian buster/main armhf libgl-dev armhf 1.3.0-7~bpo10+1 [100 kB]
Scaricamento di:3 http://archive.raspberrypi.org/debian buster/main armhf libgl1-mesa-dev armhf 19.3.2-1~bpo10+1~rpt4 [49,4 kB]
Scaricamento di:4 http://raspbian.mirror.garr.it/mirrors/raspbian/raspbian buster/main armhf libglu1-mesa-dev armhf 9.0.0-2.1 [169 kB]
Scaricamento di:5 http://raspbian.mirror.garr.it/mirrors/raspbian/raspbian buster/main armhf libwxgtk3.0-0v5 armhf 3.0.4+dfsg-8 [3.556 kB]
Scaricamento di:6 http://raspbian.mirror.garr.it/mirrors/raspbian/raspbian buster/main armhf wx-common armhf 3.0.4+dfsg-8 [169 kB]
Scaricamento di:7 http://raspbian.mirror.garr.it/mirrors/raspbian/raspbian buster/main armhf libwxgtk3.0-dev armhf 3.0.4+dfsg-8 [138 kB]
Recuperati 4.199 kB in 4s (1.027 kB/s)   
Selezionato il pacchetto libglx-dev:armhf non precedentemente selezionato.
(Lettura del database... 190006 file e directory attualmente installati.)
Preparativi per estrarre .../0-libglx-dev_1.3.0-7~bpo10+1_armhf.deb...
Estrazione di libglx-dev:armhf (1.3.0-7~bpo10+1)...
Selezionato il pacchetto libgl-dev:armhf non precedentemente selezionato.
Preparativi per estrarre .../1-libgl-dev_1.3.0-7~bpo10+1_armhf.deb...
Estrazione di libgl-dev:armhf (1.3.0-7~bpo10+1)...
Selezionato il pacchetto libgl1-mesa-dev:armhf non precedentemente selezionato.
Preparativi per estrarre .../2-libgl1-mesa-dev_19.3.2-1~bpo10+1~rpt4_armhf.deb...
Estrazione di libgl1-mesa-dev:armhf (19.3.2-1~bpo10+1~rpt4)...
Selezionato il pacchetto libglu1-mesa-dev:armhf non precedentemente selezionato.
Preparativi per estrarre .../3-libglu1-mesa-dev_9.0.0-2.1_armhf.deb...
Estrazione di libglu1-mesa-dev:armhf (9.0.0-2.1)...
Selezionato il pacchetto libwxgtk3.0-0v5:armhf non precedentemente selezionato.
Preparativi per estrarre .../4-libwxgtk3.0-0v5_3.0.4+dfsg-8_armhf.deb...
Estrazione di libwxgtk3.0-0v5:armhf (3.0.4+dfsg-8)...
Selezionato il pacchetto wx-common non precedentemente selezionato.
Preparativi per estrarre .../5-wx-common_3.0.4+dfsg-8_armhf.deb...
Estrazione di wx-common (3.0.4+dfsg-8)...
Selezionato il pacchetto libwxgtk3.0-dev:armhf non precedentemente selezionato.
Preparativi per estrarre .../6-libwxgtk3.0-dev_3.0.4+dfsg-8_armhf.deb...
Estrazione di libwxgtk3.0-dev:armhf (3.0.4+dfsg-8)...
Configurazione di wx-common (3.0.4+dfsg-8)...
Configurazione di libwxgtk3.0-0v5:armhf (3.0.4+dfsg-8)...
Configurazione di libglx-dev:armhf (1.3.0-7~bpo10+1)...
Configurazione di libgl-dev:armhf (1.3.0-7~bpo10+1)...
Configurazione di libglu1-mesa-dev:armhf (9.0.0-2.1)...
Configurazione di libwxgtk3.0-dev:armhf (3.0.4+dfsg-8)...
update-alternatives: viene usato /usr/lib/arm-linux-gnueabihf/wx/config/gtk2-unicode-3.0 per fornire /usr/bin/wx-config (wx-config) in modalità automatica
Configurazione di libgl1-mesa-dev:armhf (19.3.2-1~bpo10+1~rpt4)...
Elaborazione dei trigger per man-db (2.8.5-2)...
Elaborazione dei trigger per libc-bin (2.28-10+rpt2+rpi1)...
pi@raspberrypi:~ $ 


pi@raspberrypi:~ $ apt list --installed | grep "wx"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libwxbase3.0-0v5/oldstable,now 3.0.4+dfsg-8 armhf [installato, automatico]
libwxbase3.0-dev/oldstable,now 3.0.4+dfsg-8 armhf [installato]
libwxgtk3.0-0v5/oldstable,now 3.0.4+dfsg-8 armhf [installato, automatico]
libwxgtk3.0-dev/oldstable,now 3.0.4+dfsg-8 armhf [installato]
libwxgtk3.0-gtk3-0v5/oldstable,now 3.0.4+dfsg-8 armhf [installato, automatico]
wx-common/oldstable,now 3.0.4+dfsg-8 armhf [installato, automatico]
wx3.0-headers/oldstable,now 3.0.4+dfsg-8 all [installato, automatico]

**Comment by ahall41** [comment] 2022-04-07 12:16
Not sure if this is significant, but the Help window was OK on release 3.6.2; I've got several flavours of linux, all with wx 3.0.4; @paolo2504 - have you tried building a slightly earlier release?
With a later build (3.6.4), minimise and maximise are missing from Help, and it appears on top of other GO panels.

**Comment by paolo2504** [comment] 2022-04-07 14:03
ahall41, yes: as far as i remember this issue disappeared in earlier release...
Anyway, this is not a fatal error until you dont get to it.. Just dont use Help from Settings tabs. Soon or after it will be fixed; i suppose other pull requests are more important.

**Comment by oleg68** [comment] 2022-04-07 19:57
> ok. using another sd i made as follows. afaik, libraries were not updated... and issue is the same.
> i also tried to set libwxbase3.0-0v5 but it says already latest version 3.0.4+dfsg-8 installed...

Seems you are using the `oldstable` version of Raspbian instead of the `stable`.

**Comment by paolo2504** [comment] 2022-04-08 06:50
Oleg:
1. I’m using raspberry os 32 bit legacy downloaded from raspberry org site
2. The issue is present in windows 10 as well as in raspberry os

**Comment by oleg68** [comment] 2022-04-12 20:11
@paolo2504 I've tested Help with 3.6.4-1 on Windows 10.

1. File -> Settings -> Help opens the Help window on top of the Settings window. The Settings dialog is not more selectable,  I cann't reproduce the behaviour you mentioned.
2. After click on `Minimize`, the help window closes but a small rectangle appears at the bottom left conner of the screen. When I click on it the Help window restores.
3. After minimizing the Help window the Settings dialog becomes selectable again. After closing it, there is no way to reopen the help window.

The third point is a bug. I'll try to fix it.

**Comment by paolo2504** [comment] 2022-04-15 10:42
Oleg, here is an update of the issues and how to reproduce them. I found three different bugs depending on calling Help from Menu or from Settings. 
I've tested as follows using latest 3651.

---------------------------------------
First issue: Menu Help/Settings Help
1 launch GO
2 from Menu: Help/Help
  The Help dialog opens but it takes foreground handle. You can navigate through the help sections but the underlaying 
  GO taskbar is not fully visible; depending or not it was moved before calling Help, some parts of the Menu 
  may or not be visible and accessible with the mouse. (this is first bug).

Second issue: Menu Help/Settings Help
3 (with Help dialog still opened as done in previous steps) choose File/Settings and click the Help pushbutton (no matter 
  from which tab).
  A Help dialog opens but nothing can be selected (second bug). The only way to close it is to get back to Settings dialog
  and Cancel it : the Settings dialog closes and the original Help dialog opened from Menu gains back control)

Third issue: Settings Help/Settings Help
1 launch GO
2 open Settings (File/Settings)
3 click on Help button (Help opens) then click the button again (you can also click Help first, then select another tab,
 then Help again from there: it is the same...). The Help items work fine
4 now click Cancel to close the Settings dialog: both Settings and Help dialogs close.
5 click File/Help: nothing happens (no Help dialog opens). This is the third issue.
  Even opening again the Settings dialog and doing Help from there won't work.
  The only way to reset Help handle is to close and restart GO.

 Hope this helps.

**Comment by oleg68** [comment] 2022-04-22 18:08
> First issue: Menu Help/Settings Help

I can not reproduce this. Have I made all right?

https://user-images.githubusercontent.com/11586506/164770482-1898caf8-b87f-47e6-830c-baf893573645.mp4

**Comment by oleg68** [comment] 2022-04-22 18:12
> Second issue: Menu Help/Settings Help
> 3. repeat steps 1., 2. (Help dialog is now open) and choose File/Settings and click an Help pushbutton (no matter
> from which tab).
> A Help dialog opens but nothing can be selected (**second bug**). The only way to close it is to get back to Settings dialog
> and Cancel it : the Settings dialog closes and the original Help dialog opened from Menu gains back control).

Yes, I could reproduce it.

**Comment by oleg68** [comment] 2022-04-22 18:17
> 4 click Cancel to close the Settings dialog: both Settings and Help dialogs close.
> 5 now, click File/Help: nothing happens (no Help dialog opens). This is the **third bug**.

Yes, I can confirm it.

**Comment by paolo2504** [comment] 2022-04-24 19:09
Regarding first issue…
You don’t see it because the taskbar opens outside the help dialog…
When you click on help/Help the help dialog opens under the taskbar so that you have access to all menu voices..
Try move the help dialog over the taskbar : this way you are going to have access ONLY to visible menu items. This happens because the Help dialog probably has some property to be set always in front of any other windows. This way, unfortunately, the items on the taskbar are accessible only if fully visible. As I wrote in some previous note, this is not correct in Windows. The “child” dialogs (like the Help one) should open and stay independent from the taskbar. Think for example how panels open: they are indipendent and when you click on taskbar you have full control on it (and panels go on background…).
Hope i have been enough clear… look also to the gohelpdialog_1.mp4 recording…

**Closed** 2022-04-29 18:09 UTC
Labels: bug
