### ISSUE TITLE
GO freezing issues

### ISSUE THREAD

**Issue by obw-go** [GrandOrgue/grandorgue#1956] opened 2024-07-30 14:30 UTC
When out of the blue the Panic button is pushed or the Panic option is choosen from the menu, GO freezes.

When I changed the language to Dutch, quit GO and start GO again and try to change language to English,  Go freezes.

**Comment by rousseldenis** [comment] 2024-07-30 15:13
Hi @obw-go, could you provide more information?

On which environnement you are (win, linux, Mac), which version of GO you are using.

Thanks

**Comment by larspalo** [comment] 2024-07-30 20:27
> After building and installing the package grandorgue_3.14.3-0_localamd64.deb and running GO this freezing occurs with the two examples given.

Just FYI, for local development there's more or less no point in creating the package and/or installing GO (that's done to facilitate easy distribution). You can equally well just run the compiled binary from the /bin directory and skip all the extra steps.

**Comment by obw-go** [comment] 2024-07-30 21:38
@larspalo  Thx for the hint - this saves me time!

**Comment by oleg68** [comment] 2024-07-31 08:15
This issue looks like one was fixed with https://github.com/GrandOrgue/grandorgue/commit/faa554bc7202cd323970243fe8f1ee0ea4b05b7a.

@obw-go  Could you try to disable sample set caching and to delete the existing cache files. Will GO still hang?

If no then the right  way to fix it is to update your source tree with the latest one from github and to rebuild GrandOrgue.

**Comment by obw-go** [comment] 2024-07-31 09:57
@larspalo 
> 
> Just FYI, for local development there's more or less no point in creating the package and/or installing GO (that's done to facilitate easy distribution). You can equally well just run the compiled binary from the /bin directory and skip all the extra steps.

I looked into the bin directory, but did not find a program icon to start GO...:
![bin_no_program_icon](https://github.com/user-attachments/assets/f7785d1b-cb67-4590-8666-5fc2c1a0d815)

**Comment by obw-go** [comment] 2024-07-31 10:06
@oleg68 
> Could you try to disable sample set caching and to delete the existing cache files. Will GO still hang?
I removed the Cache (using the menu-option), and after that went to the Settings menu-option and disabled the option Automatic Cache Management (or something like this - I see the Dutch text now)... After clicking OK the program freezes again.

**Comment by oleg68** [comment] 2024-07-31 10:39
> @oleg68
> 
> > Could you try to disable sample set caching and to delete the existing cache files. Will GO still hang?
> 
> I removed the Cache (using the menu-option), and after that went to the Settings menu-option and disabled the option Automatic Cache Management (or something like this - I see the Dutch text now)... After clicking OK the program freezes again.

You have to start GrandOrgue again for using these settings. Please check that the cache file does not exist. Does  GO hang?

> Do you know which git commando I have to use in order to refresh the source stuff on my local computer?

`git pull` or `git fetch ; git merge origin/master`.

**Comment by obw-go** [comment] 2024-07-31 11:08
> You have to start GrandOrgue again for using these new settings. Please check that the cache file does not exist. Does GO hang?

I first removed the files from the Cache directory by hand before starting GO. In the Cache directory I can see again two files related to the demo organ popping up. When I do the checks (pushing Panic button, change language option in the Settings), the program no longer freezes.... So it seems that the freezing is related to something in the cache file(s)...

**Comment by obw-go** [comment] 2024-07-31 11:14
> git fetch ; git merge origin/master

After this command I got the screenmessage:
![nothing_refreshed](https://github.com/user-attachments/assets/dcf1f5ff-b26d-4bbe-a0b9-a788cd222de5)

So it seems nothing in the source needed to be refreshed?

**Comment by oleg68** [comment] 2024-07-31 11:15
> So it seems that the freezing is related to something in the cache file(s)...

Update your GO codebase to peak the fix https://github.com/GrandOrgue/grandorgue/commit/faa554bc7202cd323970243fe8f1ee0ea4b05b7a and rebuild GrandOrgue. Then enable the cache again. Does GO freese?

**Comment by obw-go** [comment] 2024-07-31 11:18
> Update your GO codebase to peak the fix [faa554b](https://github.com/GrandOrgue/grandorgue/commit/faa554bc7202cd323970243fe8f1ee0ea4b05b7a)

Sorry Oleg - this "codebase to peak the fix" is Chinese for me!

**Comment by oleg68** [comment] 2024-07-31 11:41
@obw-go what is your current git branch?

`git branch`

**Comment by obw-go** [comment] 2024-07-31 12:13
> @obw-go what is your current git branch?
> 
> `git branch`

![git_branch](https://github.com/user-attachments/assets/a76024d9-46a9-4cb0-b119-50ac7d020fa6)

And installation did take considerable time and space...
And still "git branch" not working.
So I want to remove again what was installed and takes useless space now... Do you know how I can do that?

**Comment by obw-go** [comment] 2024-07-31 13:00
@oleg68 
> what is your current git branch?

* master

**Comment by oleg68** [comment] 2024-07-31 17:12
@obw-go Then `git pull` should help you.

**Comment by obw-go** [comment] 2024-07-31 19:47
@oleg68     ThxA  This worked - I saw some updating of some files done...

**Comment by oleg68** [comment] 2024-08-01 11:30
Does the freesing still occur with the new code and the cache enabled?

**Comment by obw-go** [comment] 2024-08-07 20:32
@oleg68 
Also after updating my local system with the last Release files, the freezing persists when I change an option in the Settings and click on OK. After that I have to choose for "Force Quit" every time...

**Comment by oleg68** [comment] 2024-09-29 06:13
@obw-go Could you post the screenshot of Settings->Audio tab here?

**Comment by obw-go** [comment] 2024-09-29 11:28
@oleg68 
Hi Oleg,

Here it is:

![Settings_Audio](https://github.com/user-attachments/assets/8b9c48b6-bf81-4f50-9cb1-19d4f47eeb37)

**Comment by oleg68** [comment] 2024-09-29 11:46
@obw-go Does the issue still exist with the last GrandOrgue version?

**Comment by obw-go** [comment] 2024-09-29 13:38
@oleg68 
Yes - it still happens with the last version as well.

**Comment by oleg68** [comment] 2024-09-29 14:10
@obw-go because I cannot reproduce this issue, could you export your u20 virtual machine to an .ova file and put in somewhere (ex. Google Drive)? Don't forget to change your password in the virtual machine before the export.

**Comment by oleg68** [comment] 2024-12-14 17:32
@obw-go I'm closing this issue because I cannot reproduce it. Feel free to reopen the issue if the problem still exists and your are ready to export your virtual machine and to give it to me for reproducing.

**Closed by oleg68** 2024-12-14 17:32 UTC
