### ISSUE TITLE
GO crashes at startup

### ISSUE THREAD

**Issue by rousseldenis** [GrandOrgue/grandorgue#1988] opened 2024-08-24 11:05 UTC
Last release of GO.

2 seconds before the organ is loaded (progress bar at the end), GO crashes without error message.

@oleg68 could you remind how to produce crash dump on Ubuntu?

Thanks

**Comment by oleg68** [comment] 2024-08-24 19:32
@rousseldenis Try to delete the cache of the organ is loaded. Does the crash still occur?

**Comment by rousseldenis** [comment] 2024-08-25 14:59
> @rousseldenis Try to delete the cache of the organ is loaded. Does the crash still occur?

Yes.

In fact, GrandOrgue loads correctly randomly one time on four/five time (quite annoying).

I did memory tests to check an hardware problem but it seems OK.

I've done a crash dump with kdump. I have a crash file but not readable. I'm wondering if there are more intuitive tools?

**Comment by oleg68** [comment] 2024-08-25 18:40
> In fact, GrandOrgue loads correctly randomly one time on four/five time (quite annoying).

Do the craches occur with every sample set including the demo one? Or it crashes only with certain sample sets?

I have a crash file but not readable. I'm wondering if there are more intuitive tools?

The crash file can be opened and expected with a gdb debuger. It would be great to obtain a stack trace but it requires to have GrandOrgue with debug symbols. Usually local builds (without packaging to .deb) provides such builds.

**Comment by rousseldenis** [comment] 2024-08-28 15:37
To load the organ, I need to interrupt first loading, then reload the organ. Works at each time

**Comment by oleg68** [comment] 2024-09-03 18:51
@rousseldenis You haven't still answered my question ``Do the craches occur with every sample set including the demo one? Or it crashes only with certain sample sets?``

**Comment by rousseldenis** [comment] 2024-09-04 07:23
> @rousseldenis You haven't still answered my question `Do the craches occur with every sample set including the demo one? Or it crashes only with certain sample sets?`

That's because I had no time yet to test that. I'll come later with some figures.

**Comment by rousseldenis** [comment] 2024-09-04 18:57
I saw gtk process each time at 100% CPU before crash. The same problem for every sample set.

As Ubuntu 24 is out, I tried upgrading and installed wx32 version.

After several organ reloads, everything is working correctly.

So, maybe closing this if nobody has the same problem.

**Comment by oleg68** [comment] 2024-11-05 18:50
@rousseldenis I'm close this issue because nobody can reproduce it.

**Closed** 2024-11-07 05:12 UTC
