### ISSUE TITLE
Cache created for organ packages even if not set in settings

### ISSUE THREAD

**Issue by paolo2504** [GrandOrgue/grandorgue#957] opened 2022-01-12 22:57 UTC
I found that organ cache files are created when using option "install organ package" even if the "Automatically manage cache" i not set in Settings/cache option. 
Not a big issue indeed but i wonder if it is by design for some reason.
Note: doing File/open to load new organs for the first time, correctly does not create the cache if the above option is not set.

**Comment by jason-barba** [comment] 2022-01-13 08:52
A wild guess, but since a .orgue file is a zip archive it has to be extracted to somewhere before GO can read the ODF. Could the cache be the place?

**Comment by paolo2504** [comment] 2022-01-13 12:39
> 

It could be. Nice thought.

**Comment by willeke1234** [comment] 2022-01-26 09:27
Is the file a small .idx file or a big .cache file?

**Comment by paolo2504** [comment] 2022-01-26 10:58
It’s the cache file.

**Comment by oleg68** [comment] 2023-04-17 18:51
While installing an organ package, the small .idx file is created in the Cache directory. No .cache file appears there.

I close this issue because I cann't reproduce it with GrandOrgue 3.11.0-1. Feel free to reopen this issue, if you reproduce it and you are ready to provide additional info.

**Closed by oleg68** 2023-04-17 18:51 UTC
Labels: bug
