### ISSUE TITLE
Enchance Midi Settings

### ISSUE THREAD

**Issue by oleg68** [GrandOrgue/grandorgue#703] opened 2021-08-18 19:16 UTC
Now GrandOrgue automatically enables all available midi devices and then allows to disable some of them in Midi Settings.

GO keeps the names of disabled midi devices.

Sometimes midi devices change their names across system restart. For example, the name of alsa device names contain the midi port number that depends on the device initialisation order and can vary. In this case the old device with the new name will be automatically enabled that may be not desirable.

I'm going to make the following changes:
- [x] Introduce a subsystem filter for devices (alsa, jack, core etc)
- [x] Introduce a settings ``Enable new devices automatically``, by default enabled.
matched by regex
- [x] Introduce the setting not to check midi on startup #796 

Some other midi enchancements will be done in #885

**Comment by ajvdw** [comment] 2021-09-24 18:32
I'd like to enable/disable midi devices per RtMidi API (Jack, ALSA, etc?)

**Comment by oleg68** [comment] 2021-09-24 19:40
@ajvdw I've added it to the to-do list

**Comment by oleg68** [comment] 2021-11-20 12:39
@rousseldenis @larspalo 

Because this issue is not obvious, we need to discuss it. I'd ask you to post your thoughs and suggestions here.

**Comment by larspalo** [comment] 2021-11-20 19:29
The issue of (USB) MIDI devices changing names is not new. In rev 2174 Martin actually patched RtMidi because it's really a big part of the issue. With the updates to RtMidi those patches may long be gone now (I'm not certain if they were merged upstream or not). If the same effect can be achieved with regex comparison of devices it's all fine and dandy. But if possible, the list of devices should not name them so that any confusion will be created even if the port number changes but match the stored device to what the system presents, ideally in such a way that the user will never notice it. Otherwise it seems to be a good idea to enable a subsystem filter so that a lot of the "noise" caused by probing at startup can be eliminated once a working setup is achieved.

**Closed** 2021-12-11 10:37 UTC
Labels: enhancement
