### ISSUE TITLE
Crash when closing an organ

### ISSUE THREAD

**Issue by willeke1234** [GrandOrgue/grandorgue#1678] opened 2023-10-11 18:30 UTC
Every now and then closing an organ causes a crash or strange behavior. The strange behaviour could be something like creating a cache while caching is off or pressing a key when a stop is pulled. The crash occurs more often if the organ uses a lot of memory, but it can also occur with smaller organs. Steps to reproduce:

Load or open an organ
Close
Repeat

GO version: 3.13.0

[Crash Reports.zip](https://github.com/GrandOrgue/grandorgue/files/12873434/Crash.Reports.zip)

**Comment by oleg68** [comment] 2023-10-15 17:41
Is it a standard GO build from github or it is a custom build? If it is a custom build, could you reproduce this issue with the standard build?

**Comment by oleg68** [comment] 2023-10-15 17:50
Do you have any warnings like ``Freeing non-empty memory pool`` in the log window before the crash?

**Comment by willeke1234** [comment] 2023-10-21 13:55
I don't know if it's related but if I start GO, load an organ (Friesach) and press the Panic button many times then GO hangs.

[Sample of GrandOrgue v3.13.0.zip](https://github.com/GrandOrgue/grandorgue/files/13060871/Sample.of.GrandOrgue.v3.13.0.zip)

**Comment by oleg68** [comment] 2023-11-04 16:02
@willeke1234 could you try the fix of closing an organ from https://github.com/oleg68/GrandOrgue-official/actions/runs/6755745068 (the source code in https://github.com/oleg68/GrandOrgue-official/tree/bugfix/macos-close)?

**Comment by willeke1234** [comment] 2023-11-05 11:42
@oleg68  I tried the downloaded X86 build and an ARM build, both still crash.

**Comment by oleg68** [comment] 2023-11-05 13:52
> @oleg68 I tried the downloaded X86 build and an ARM build, both still crash.

Could you post here the crash report from the new version?

**Comment by willeke1234** [comment] 2023-11-05 16:41
More crash reports: 
[Crash Reports 2.zip](https://github.com/GrandOrgue/grandorgue/files/13260231/Crash.Reports.2.zip)

**Comment by oleg68** [comment] 2023-11-05 17:46
Was the organ cached or not?

**Comment by willeke1234** [comment] 2023-11-05 19:27
Caching is off.

**Comment by oleg68** [comment] 2023-11-06 08:41
Because I cann't reproduce this issue, the only way of discovering this problem is to make some debugging changes in GO, to compile it on your environment, to run it and to post here the debug output and crash reports.

@willeke1234, do you agree to do in this way?

**Comment by oleg68** [comment] 2023-11-06 15:33
@willeke1234 If you are ready to participate in debugging, please
1. Take the sources from https://github.com/oleg68/GrandOrgue-official/tree/bugfix/macos-close
2. Compile on m1
3. Run GrandOrgue from a terminal window
4. Do `File->Debug Close`
5. Do `File->Close`
6. Post here the terminal output
7. If a crash occured, post here the crash report

**Comment by willeke1234** [comment] 2023-11-06 17:18
@oleg68 

Terminal output:

```
GOMemoryPool::AllocatePool: before mmap: 12884901888
GOMemoryPool::AllocatePool: after mmap: 0x280000000
GOFrame::OnMenuDebugClose: before allocating the pool
GOMemoryPool::AllocatePool: before mmap: 12884901888
GOMemoryPool::AllocatePool: after mmap: 0x580000000
GOFrame::OnMenuDebugClose: allocated the pool, 12884901888 bytes
GOMemoryPool::FreePool: before munmap: 0x580000000 12884901888
GOMemoryPool::FreePool: after munmap
GOFrame::OnMenuDebugClose: after dellocating the pool
libc++abi: terminating due to uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
zsh: abort      
grandorgue@Virtuele-machine-van-GrandOrgue GrandOrgueBuild % 
```

Crash report: [Crash Report.txt.zip](https://github.com/GrandOrgue/grandorgue/files/13269838/Crash.Report.txt.zip)

I did some debugging and put a breakpoint on `GOSoundTouchWorkItem::~GOSoundTouchWorkItem()`. It's hit before the crash in `GOSoundTouchWorkItem::Run(GOSoundThread*)`. If I can help with more debugging, please let me know.

**Comment by nanoufo** [comment] 2023-11-07 17:57
I managed to cause SIGSEGV when closing GrandOrgue on ubuntu by adding sleep() after retrieving a work item in GOSoundThread.
Also I made a fix: [link](https://github.com/nanoufo/grandorgue/tree/afd1b7fa625f04044dae42a3110317cf7fbf972c),

I hope the same fix works for that issue.
@willeke1234 Could you compile it and see if the problem remains?

**Comment by willeke1234** [comment] 2023-11-08 14:24
The fix works, GO reloaded 50 times and no crashes.

**Closed** 2023-11-12 16:44 UTC
