### ISSUE TITLE
Uninstallation under Windows

### ISSUE THREAD

**Issue by paolo2504** [GrandOrgue/grandorgue#951] opened 2022-01-06 19:26 UTC
Today i unistalled GO under Win 10 (to make a fresh install from scratch) and foud as follows:
1. folder Programs\Grandorgue removed because not empty (but this is not shown in the uninstall phase). subfolder bin and share are still present and not empty (see below).
2. Cache and Data folders are not removed

Btw: is there any hint regarding installing GO or simply manually extract package files somewhere on the pc ? Any concern on doing one way or the other ?
thanks

**Comment by oleg68** [comment] 2022-01-09 16:00
> 1. folder Programs\Grandorgue removed because not empty (but this is not shown in the uninstall phase). subfolder bin and share are still present and not empty (see below).

Yes. ``c:\Program Files\GrandOrgue\share\GrandOrgue\help`` remains. It is a bug.

> 2. Cache and Data folders are not removed.

It is by design. Uninstalling grandorgue should only remove files from ``c:\Program Files\GrandOrgue`` but not the user settings.  It is goes this way because install/uninstall works by an administrator account, but the configuration files are stored in user accounts. Several users may share the same executables and have their own configuration, so the configuration files are out of scope the GrandOrgue installer,

> is there any hint regarding installing GO or simply manually extract package files somewhere on the pc ? Any concern on doing one way or the other ?

- When you install GrandOrgue with the installer
    1. The executables appear at the shared location and any user may use them.
    2. The installer creates a desktop menu entry for GrandOrgue.
    3. Only one of GrandOrgue version can be installed at the same time.

- When you unpack the package
    1. By default other users don't have an access for these files.
    2. You do not have a desktop menu entry, so you have to start GrandOrgue with a file explorer.
    3. You may unpack as many versions of Grandorgue to different directories as you want. Moreover you may have the old verion installed with the installer and to unpack new versions at the same time.
 
Usually users unpack the package without installation whey they want to test a new version (possible, an intermediate build with extra debug information) or to compare different versions.

But it is recommended to install the selected version for further usage.

**Comment by paolo2504** [comment] 2022-01-09 18:25
1.
aknowledge. Not only share...\help subfolder is left. also C:\Program Files\GrandOrgue\bin is left with some files, as far as i remember (i took screenshot but then i deleted it...) from libjack64.dll to zlib1.dll.
)
![immagine](https://user-images.githubusercontent.com/50132661/148695204-1358eb0a-b901-438f-8809-47c6efecc497.png)


2.
aknowledge. Nevertheless, I'm sure most users don't have many accounts on their own pc so i believe it could be nice have the option, during uninstall, to remove all files (settings, cache, dix, cmb. The script tool does have the option to set user preference about deleting or not the user settings.

**Comment by oleg68** [comment] 2022-01-09 19:04
> aknowledge. Nevertheless, I'm sure most users don't have many accounts on their own pc so i believe it could be nice have the option, during uninstall, to remove all files (settings, cache, dix, cmb. The script tool does have the option to set user preference about deleting or not the user settings.

It is impossible because it requires that the uninstaller would run by two different user accounts.

**Comment by paolo2504** [comment] 2022-01-10 09:47
Uhm. So I was wrong. I remembered that with Nullsoft or Inno Setup it was possible to specify removal of user settings as well. No problem.

**Comment by oleg68** [comment] 2022-04-11 19:10
@paolo2504 the reason while some files are not deleted from the ``Program Files\GrandOrgue` is that they are used by a running application. The workarounds are either reboot Windows before uninstalling GrandOrgue or to open `Task Mamager`, find the ``Virtual Pipe Organ Software`` application ane click on ``End Task``.

I am making some research why GrandOrgue does not finish on exit.

**Comment by oleg68** [comment] 2022-04-12 18:50
@paolo2504 I managed to reproduce the problem with uninstall with GrandOrgue 3.6.4-1 when an Impulse Reveberation was enabled in the settings. The reason was the same as in #983: when a user exits from GrandOrgue it closes all windows and then hangs on closing sound. So the application was still running and preventing deletion it's files.

I can reproduce the problem neither on [3.6.5-0.5](https://github.com/GrandOrgue/grandorgue/suites/6062437918/artifacts/209349827) with reveberation enabled nor on 3.6.4-1 with reveberation disabled: all files are deleted from ``c:\Program Files\GrandOrgue`` as well as the folder itself.

Please feel free to reopen this issue if the uninstallation problem occurs with the new version.

**Closed by oleg68** 2022-04-12 18:50 UTC
Labels: bug
