### ISSUE TITLE
GrandOrgue crashes after loading organs several times

### ISSUE THREAD

**Issue by paolo2504** [GrandOrgue/grandorgue#707] opened 2021-08-31 10:12 UTC
A nice-to-have feature would be, imho, to auto-close already open organ upon loading a new one.
At present, GO keeps any organ open until memory is full (considering the large ram request of most samplesets, this happens very often, even after loading just 2 organs). 
When memory is full, GO does crash without warning and closes itself, disappearing from desktop.
I write this post here (not in discussion/ideas) because it could be considered an issue as GO brutally closes.

**Comment by oleg68** [comment] 2021-11-15 14:13
@Jean-Gabriel1982 

> the automatic closing of an organ when another # 707 is loaded (which can be very practical when plays a ceremony) ..

Do you really often change an organ when you are playing a ceremony?

**Comment by Jean-Gabriel1982** [comment] 2021-11-15 14:20
> @Jean-Gabriel1982
> 

> Do you really often change an organ when you are playing a ceremony?

mmm... it depends on the music I play :) 
For example if I want to play French baroque music and I use a mesotonic temperament organ, I have to change by a "principal organ" one for accompaniments ... in mesotonic I think the Choir will not be a fan :p

**Comment by oleg68** [comment] 2021-11-15 14:25
Yes, non-equal temperaments are difficult for the choir...

But as a temporary workaround I can suggest you not to load different organs, but just to change the temperament with the Audio/Midi->Temperament menu.

**Comment by Jean-Gabriel1982** [comment] 2021-11-15 14:51
> Yes, non-equal temperaments are difficult for the choir...
> 
> But as a temporary workaround I can suggest you not to load different organs, but just to change the temperament with the Audio/Midi->Temperament menu.

yes I understand that it can be done, but you will still not have the "color" of the classical French organ ..

For example, playing the Cavaillé-Coll organ in Caen and changing the temperament to play baroque is not going to "sound" at all like a St Michel in Thiérache ...

**Comment by oleg68** [comment] 2021-11-15 18:46
> Well, I'm not so sure that #707 is valid at all. GO is supposed to be able to be multi instanced - allowing having multiple organs open at the same time. It's the users responsibility to close an opened organ that's no longer wanted. This is all by design, not by lack of understanding!

@larspalo 

As I understand, when GO loads an organ it takes some amount of memory.
When the user closes this organ (but but does not exit from GO),  the memory should return to the heap and should become available for loading the next organ. If GO does not do it, then it is a bug abd should be fixed.

When the user loads a new organ without closing the old organ, it must be closed automatically and the memory  must return to the heap. If the memory is returned only when the user closes manually but not when the user loads the next organ, then it is also a bug,

> GO is supposed to be able to be multi instanced - allowing having multiple organs open at the same time. 

But how to use several organs?

**Comment by larspalo** [comment] 2021-11-15 19:06
> When the user closes this organ (but but does not exit from GO), the memory should return to the heap and should become available for loading the next organ. If GO does not do it, then it is a bug abd should be fixed.

Yes, absolutely. That is if the organ is closed the memory should absolutely be freed, otherwise we have a memory leak - model huge!

> When the user loads a new organ without closing the old organ, it must be closed automatically and the memory must return to the heap. If the memory is returned only when the user closes manually but not when the user loads the next organ, then it is also a bug,

No. This is by design. The user **MUST** actively close an organ to return the memory, otherwise the organ will stay opened and continue to be playable.

> But how to use several organs?

You can start multiple organs from the command line when you start GO. Or, from within the GUI, just load multiple organs and connect each of them to correct MIDI keyboards and play. You can play multiple manuals/stops from different organs on the same MIDI keyboard, no issues. Each organ will have it's own panel entry/entries.

**Comment by larspalo** [comment] 2021-11-15 19:10
Actually, there do seems to be some bugs with this. Needs to be investigated! But GO was intended to be able to handle multiple instances.

**Comment by larspalo** [comment] 2021-11-15 20:02
So, if I start multiple instances of GO from the commandline with -i UniqueInstanceName for each of them it works as it's kind of supposed to do - I can have multiple organs loaded at the same time and play them all. I can even have different audio devices and settings for the different instances. The question now is, was it ever working from within the GUI within a single instance? Would we like to have the possibility to have multiple organs playable at the same time and be able load them from the GUI, even if it would be with single instance audio settings?

It would be pretty simple to implement an auto close before opening if it's not happening, and "fix" this issue if that's indeed the desired behaviour. And of course, the memory management must be done correctly (which it might not be presently). I just wonder if there could have been another thought about this somewhere down the road...

**Comment by oleg68** [comment] 2021-11-15 20:26
@larspalo But when I have opened the first organ and then I'm opening the second organ with File->Open or File->Open Recent, the panel of the first organ **disappears**. The user becomes able neither to play the first organ nor to close it manually. If the first organ rests in the memory then I consider it as a bug.

**Comment by Jean-Gabriel1982** [comment] 2021-11-15 20:34
on the one hand it is indeed interesting to be able to play several organs at the same time (I imagine with different sounds such as baroque or symphonic) but in my opinion only to "switch" quickly from one to the other (concerts or ceremonies).

in this case indeed it will be necessary to have an overpowered computer or then to open "small" organs.

in the event that we want to play the organs at the same time I do not know if this has a musical interest except if GO can "harmonize" the temperaments, sound levels etc on the fly on several instruments at the same time .. and in this case will also require a very powerful computer.

for this last point, do the majority of GO users have such a powerful pc?
if not, is this function of playing several organs at the same time important?

otherwise, option, when the user wants to open a second instrument, GO offers him:
- close the instrument in use
Or
- open the second while keeping the first open

**Comment by larspalo** [comment] 2021-11-15 20:51
> But when a user has opened the first organ and then he is opening the second organ with File->Open or File->Open Recent, the panel of the first organ **disappears**. The user becomes able neither to play the first organ nor to close it manually. If the first organ rests in the memory then I consider it as a bug.

Yes, that's what obviously happens now. I'm trying to track the memory usage right now when opening and just opening another organ. So far, with just opening new organs I've not been able to crash and memory seems to be released. I'll try to push it to the limits and see what happens, but right now with the latest build from official GO master it seems to do the right things.

**Comment by larspalo** [comment] 2021-11-15 21:13
I've been opening and opening organs now without closing so that the memory should have been filled up many times over by now and no crash still happens. All the time I've been monitoring memory usage with `top -p PIDofGO`. When I pass over 70% of used memory everything becomes a bit sluggish, but as soon as it's complete everything on the computer works fine. I'll try to intentionally use too much memory and see what happens, but I post this before testing that in case bad things indeed happen. Would be interesting to know if others can confirm this issue with latest build, or like me not!

**Comment by larspalo** [comment] 2021-11-15 21:37
Ok. Trying to go past available memory actually crashes GO. That is a bug in itself, though it doesn't necessary have with this issue to do at all. Earlier you just got a warning stating you ran out of memory and not the whole organ could be loaded. As long as I stayed within the physical RAM limitations I could open and just open to my hearts content without issues.

**Comment by oleg68** [comment] 2021-11-16 07:03
> to auto-close already open organ upon loading a new one.
At present, GO keeps any organ open until memory is full (

@paolo2504 @Jean-Gabriel1982 

Could you describe step-by step, how to reproduce this issue?

I cann't reproduce it: when I load a new organ the old one is closed automatically. And I cann't understand what is wrong at present?

**Comment by midimusic** [comment] 2021-11-16 08:11
I agree that crashing when memory is all used up is not a good feature but otherwise being able to use multiple instances of GO is very useful. For example you can use one organ to play another one either the same or a different organ.
Currently, in my opiniom, this all works very sensibly and should be left as it is.
csw900

**Comment by oleg68** [comment] 2021-11-18 12:30
@Jean-Gabriel1982 @paolo2504 I repeat my asking to describe step by step how to reproduce the problem when the old is not closed after opening a new one?

**Comment by Jean-Gabriel1982** [comment] 2021-11-19 06:28
@oleg68 i tried to open 3 different organs (Caen, Friesach, Begard) and GO automatically closes one organ to open the chosen one, on Linux

**Comment by midimusic** [comment] 2021-11-19 08:23
On Windows if you load another organ the first one will automatically close. Memory is recovered if you close the first organ manually using the menu's "Close" option.

However this is not the right way to get more than one organ working. The proper way is to start another instance of GO and to load the second organ into that. If you must have three organs then load the third one into a third instance of GO. This does work but obviously uses a lot of memory.

csw900

**Comment by larspalo** [comment] 2021-11-19 08:44
> On Windows if you load another organ the first one will automatically close.

It's exactly the same on my Linux machine. And the truth of this statement is the real question for this issue. Not handling of multi instances.

The issue starter say that the previously loaded sampleset is not closed and have its used memory returned when another organ is opened/loaded.

Neither I, nor Oleg seem to be able to reproduce this issue. If this issue should be regarded with any validity at all we must get means to reproduce it or hard evidence of what's happening on the users system. If that's not provided the issue will be closed as it's already working exactly as it's intended to.

**Comment by oleg68** [comment] 2021-11-19 11:24
> On Windows if you load another organ the first one will automatically close. Memory is recovered if you close the first organ manually using the menu's "Close" option.

@midimusic Do you tell that the memory is recovered **only** if the first organ closed manually and **the memory is not recovered** if the organ is closed automatically when loading another organ?

**Comment by midimusic** [comment] 2021-11-19 14:35
@oleg68 
The memory is also recovered automatically if you load another organ without formally closing the first. 

The only time memory is not recovered is if you close the organ by clicking on the X at the top right of the organ. However if you then load another organ the memory is recovered before the new organ loads.

As far as I can tell on Windows everything works as I would expect it to.

csw900

**Comment by larspalo** [comment] 2021-11-19 15:18
> The only time memory is not recovered is if you close the organ by clicking on the X at the top right of the organ.

You don't close the **organ** with the x in the right top of that panel. You just close the panel. The organ is still playable and you can have other panels active instead if you so with. And it's still possible to bring back in the main organ panel from the Panel->OrganName menu.

**Comment by paolo2504** [comment] 2021-11-20 10:06
hi all. I've just made right now a quick test with latest release 3.4.2.1 on WIndows 10.
I experienced as follows:
a) i confirm memory is not released when a new organ is loaded
b) loading the same organ over and over is like loading new organs. For example, i loaded the Grandorgue Demo V1, then i loaded it a second time (it took some more time to load). By loading it a third time did cause GO to crasch without any error message (simply it disapeared). PC equipepd with just 8gb ram so i suppose with more gigas you can probably load the same organ more than 3 times before crash...
I believe test b) can be considered a second additional bug inside the main one: i mean, GO is not able to understand the organ you are loading is already loaded so it tries to load it again and crashes for lack of memory.

**Comment by oleg68** [comment] 2021-11-20 10:24
@larspalo thank you for your test. Please try to do `File->Reload` several times. Does GO crash?

**Comment by oleg68** [comment] 2021-11-20 11:04
> i loaded the Grandorgue Demo V1, then i loaded it a second time (it took some more time to load). By loading it a third time did cause GO to crasch without any error message (simply it disapeared). PC equipepd with just 8gb

But the demo organ uses only 717Mb of memory. You can see it at `File->Organ Properties` and in the Windows task manager in the `Details` tab (add the column ``Memory (shared)`` to the view).

I've tested GO on a computer with 4Gb Ram under Windows 10. I could load the Demo organ (717Mb) and Barton organ (> 2 Gb) over than 10 times without any visible memory leak in the task manager.

So I suppose you have some another reason for crash rather than a memory leak.

For descovering it please 
1. Install [the GO version with debug info](https://drive.google.com/file/d/1x95QgGoSP6gUc-ugpbl5IxbrFUefJoL6/view?usp=sharing)
2. Reload organs several times until the crash occures
3. Post the last crashdump file from  ``AppData\Local\CrashDumps`` here.

**Comment by paolo2504** [comment] 2021-11-20 12:18
Oleg,
i did as per your suggestion and found that even my intalled GO (official r3.4.2.1) is wrinting dump file.
So here below you have 5 dump files, generated today as follows (i found 3 files already under crashdump dir):

r3.4.2.1            h 10:36, 10.54, 10:55, 13:10
r3.4.3-0.847.1  h 13:12

**Comment by oleg68** [comment] 2021-11-20 12:44
@paolo2504 

1. I cann't work with dump files from official r3.4.2.1 because it does not have necessary debug information. Only r3.4.3-0.847.1 would be acceptable
2. I see only the version names but I cann't download these files. Please make a zip archive before uploading here.

**Comment by paolo2504** [comment] 2021-11-20 13:27
My fault: I forgot attaching files.. doing that soon.

**Comment by paolo2504** [comment] 2021-11-20 15:46
Here we are....
See below attached dump file: it has been created by loading three times the same organ Demo V1.
[GrandOrgue.exe.2620.zip](https://github.com/GrandOrgue/grandorgue/files/7574783/GrandOrgue.exe.2620.zip)

**Comment by oleg68** [comment] 2021-11-20 17:26
Could you try [the next build](https://drive.google.com/file/d/15z35ISLSTSB6sw3A1qSeTqQccwyN9zAT/view?usp=sharing) and post the new crash dump here?

**Comment by paolo2504** [comment] 2021-11-20 20:38
> @paolo2504
> 
> Could you try [the next build](https://drive.google.com/file/d/15z35ISLSTSB6sw3A1qSeTqQccwyN9zAT/view?usp=sharing) and post the new crash dump here?

just tested your latest build grandorgue-3.4.3-0.707.1.windows.x86_64.
Crashed on third load of the GO Demo V1

[GrandOrgue.exe.4900.zip](https://github.com/GrandOrgue/grandorgue/files/7575193/GrandOrgue.exe.4900.zip)

note: this time i kept Windows app activity open with focus on task GO. Im not sure but for a while it seems that memory is released on second load... Making some other test...

**Comment by oleg68** [comment] 2021-11-20 20:41
The crash doesn't relate to memory

**Comment by paolo2504** [comment] 2021-11-20 21:35
Oleg,
after testing i found as follows.
GO uses 7.4mb ram on load. Ram increases to 48-49mb on 1st load of Demo V1. After that, it RANDOMLY crashes: usually on 3rd load, sometime later. One time it crashed on 2nd load, one time never crashed even after 10 loads.
When GO loads the organ, ram goes down then up, then down again. When it does NOT crash it goes stable to around 51-52mb; when it is crashing, ram goes done to low values then raises, then down again then crashes. Something like 49mb-5mb-12mb... When ram goes to such low values then it means it is close to crash. 
Definitely, this up&down of the memory ALWAYS occurs; if GO keeps running it goes to nearly 48-51mb usage, when it crashes, memory falls to low up&down values then GO closes.
Hope this help.
Here below some dumps and some screenshots (look at self-explaining filenames....).

NOTE: i made test launghin the build you provided directly from the unzip folder then reloading the same organ Demo V1.
The File/Load dialog shows only that organ as expected. However, under Settings/Organs i saw all my "missing" organs due , as you know from another post, to the fact i have moved the samplesets to another location. This means that your build, even launched fomr another folder, is using , afaik, the configuration of my local GO installation isn't it ? In that case, would not this be misleading for our testing ?

paolo


[GrandOrgue.exe.1648.zip](https://github.com/GrandOrgue/grandorgue/files/7575381/GrandOrgue.exe.1648.zip)
[GrandOrgue.exe.6688.zip](https://github.com/GrandOrgue/grandorgue/files/7575382/GrandOrgue.exe.6688.zip)
[Crash Screenshots.zip](https://github.com/GrandOrgue/grandorgue/files/7575383/Crash.Screenshots.zip)

[settings and load.zip](https://github.com/GrandOrgue/grandorgue/files/7575393/settings.and.load.zip)

**Comment by oleg68** [comment] 2021-11-21 06:31
@paolo2504

According to the crash dumps, GO continues playing some sound from the organ (maybe the motor noise or some other) after it has already been closed and it's memory has been recovered and even may be is already used by a new organ. Because the old memory structures have already been destroyed, it causes the crash.

I need more time for details debugging it. Could you post here the screenshot of ``File->Settings->Audio Output``?

**Comment by paolo2504** [comment] 2021-11-21 11:56
> @paolo2504
> 
> According to the crash dumps, GO continues playing some sound from the organ (maybe the motor noise or some other) after it has already been closed and it's memory has been recovered and even may be is already used by a new organ. Because the old memory structures have already been destroyed, it causes the crash.
> 
> I need more time for details debugging it. Could you post here the screenshot of `File->Settings->Audio Output`?

![File-AudioOutput](https://user-images.githubusercontent.com/50132661/142760772-068df17e-a117-463f-8a82-f4bdad76b668.jpg)

**Comment by oleg68** [comment] 2021-11-22 18:40
@paolo2504 could you try the [next build](https://drive.google.com/file/d/1xZPIMzvMNfN_XRYMYY_t-FrnHDFn88Kc/view?usp=sharing)?

**Comment by paolo2504** [comment] 2021-11-22 23:19
> @paolo2504 could you try the [next build](https://drive.google.com/file/d/1xZPIMzvMNfN_XRYMYY_t-FrnHDFn88Kc/view?usp=sharing)?

Now looks pretty good. No crash at all after repeated tests in same conditions.
I notice that now the Panel is always opened on startup (before it didn't). Memory is stable at 51-52mb; when re-loading DemoV1, ram for GO decreases to 33mb then raises to 49 and finally to 51-52mb. A couple of times it goes up to 60mb and keeps stable on that value after that.

Good job.

**Comment by oleg68** [comment] 2021-11-23 06:42
@paolo2504 it was not a final fix yet.

**Comment by oleg68** [comment] 2021-11-23 19:54
@paolo2504 could you try the intermediate build from https://github.com/oleg68/GrandOrgue-official/actions/runs/1496393863 ?

**Comment by paolo2504** [comment] 2021-11-23 21:20
> @paolo2504 could you try the intermediate build from https://github.com/oleg68/GrandOrgue-official/actions/runs/1496393863 ?

Done with your grandorgue-3.4.4-0.2.windows.x86_64.
Reloaded DemoV1 30 times so far. No crashes. Ram mgmt looks mroe linear than with previous build: 52mb-35-45-50-52mb.
I only noticed a couple of things:
After 20 times memory usage goes up to  56, at 30 times reaches 58. This seems depending to the panel: closing it ram usage goes down to 52. If I reload again GO, ram again goes to 58 and, again, closing panel, back to 52.

Second thing CPU for a couple of seconds CPU shoes high usage at 100% even after the panel open. Then it decreases step by step to low values.

let me know if some specific testing are fine.

**Closed** 2021-11-27 16:06 UTC
Labels: bug
