### ISSUE TITLE
Not remembering Windows position or size

### ISSUE THREAD

**Issue by mattrixed** [GrandOrgue/grandorgue#1271] opened 2022-11-22 06:25 UTC
Linux Ubuntu 22.04
GO 3.9.1

Loading samplet freisach for eg window is full screen.  Move it and position it - save - close down and start up again goes back to full screen.

**Comment by oleg68** [comment] 2022-11-28 08:16
@mattrixed Could you test the same with the demo organ?

**Comment by oleg68** [comment] 2022-12-07 18:38
@mattrixed I installed ubuntu22, grandorgue 3.9.2 and I can not reproduce this problem: after restarting GrandOrgue and loading Friesach it opens at the same position and size as it was saved.

I need more information and tests from you for reproducing and fixing this problem. Are you ready to do more tests and to provide me additional information?

**Comment by mattrixed** [comment] 2022-12-13 01:28
I too with the system running in the office/studio can't replicate either - the only difference is the monitor - when connected to the small touch screen 19" 4:3 monitor 1280x1024 it doesn't save - something to do with the display size if it detects a large screen (like in office 2560x1600) its fine if its under the size of the odf if goes full screen - 

Not a big deal.....
Have installed POP! distro will see if still does it with that also....

**Comment by oleg68** [comment] 2022-12-31 18:08
This issue is related to the `Wayland` windows server. As a workaround, when you log in the ubuntu session, you may click at the settings icon (at right bottom of the window) and choose `Ubuntu on Xorg`.

**Comment by oleg68** [comment] 2023-01-01 08:25
@larspalo I remember you use Ubuntu. Do you use `wayland` or `xorg`? Do you have any issues with positioning?

I've never used `wayland` before and now I see that the windows positioning code in GrandOrgue does not work at all with wayland. wxTopWindow::GetPosition() and wxTopWindow::GetRect() returns some inadequate result.

**Comment by larspalo** [comment] 2023-01-02 17:46
@oleg68 I'm still using Ubuntu 20.04 mostly at home so it is X11 (xorg) by default. I think they changed it in 21.04 so when I decide to upgrade to 22.04 it's likely that Wayland will be used. However, window positioning works fine here with 20.04. We really should be careful to not "fix" things that really are bugs in other software, I think. If we're using the "correct" wx methods and issues still arise it's still fine and the bugs should be fixed where they really are. If, however, there are multiple ways of doing things and one version indeed gives better compatibility then that's another case... In my experience, too many "special fixes" only makes for more issues somewhere down the line and it makes the code more difficult to maintain.

**Comment by oleg68** [comment] 2023-01-02 18:27
@larspalo After some research I found two issues:

1. wayland does not support application to set their window positions. So the attempt of restore the saved position won't work. The wayland guys at https://www.mail-archive.com/wayland-devel@lists.freedesktop.org/msg41149.html suggest to allow compositors to do this job, but neither ther are any code examples of this, nor gnome-shell can do it.
2. There are an issue also with the size of pannels: on Ubuntu 22 the pannels are restored with a size larger than they were saved. 

Saved:
![VirtualBox_ub22go_save](https://user-images.githubusercontent.com/11586506/210267578-c2105cda-1bea-4815-b2f5-728698f826fa.png)

Restored:
![VirtualBox_ub22go_restore](https://user-images.githubusercontent.com/11586506/210267619-33c85a70-8256-4ae3-b4a7-6b449a5feba0.png)

This bug is present in wx 3.0.5, but it has already been fixed in wx 3.2.0.

But 3.2.0 is still absent in most linux distros. If we build GO against 3.2.0, most of users will not be able to use it out of box without installing 3.2.0 manually.

So I'd like to find some workaround.

**Comment by oleg68** [comment] 2023-01-02 19:09
@larspalo What is your opinion: what direction should we go:
1. Not to support wayland at all and put this restriction in documentation?
2. Switch GO to wx 3.2.0 with a hard way of instaling it?
3. Try to find a workaround with wx 3.0.5?

**Comment by larspalo** [comment] 2023-01-02 20:22
@oleg68 For now I think that the first option (1.) is best as it seems to be quite easy to switch to not use Wayland. As soon as major distributions ship a newer wx version we should change too.

**Comment by oleg68** [comment] 2023-01-03 07:20
@rousseldenis Do you agree with not supporting wayland?

**Comment by rousseldenis** [comment] 2023-01-03 07:53
> @rousseldenis Do you agree with not supporting wayland?

As I'm on Ubuntu 22.04 too, just tested and windows position is well saved. I suppose I'm on xorg (I'm not really used to graphics stuffs).

So, I would say yes :smiley: 

That apart, I think as there is a common workaround for that, option 1 is the best (for the time being).

**Comment by jason-barba** [comment] 2023-01-03 08:52
I run native 22.04 with wayland (default) and GO 3.6.2-debian. I haven't experienced any trouble regarding this issue.

You can check whether xorg(x11) or wayland: Open Terminal and issue cli command echo $XDG_SESSION_TYPE.

**Comment by oleg68** [comment] 2023-01-03 09:24
> I haven't experienced any trouble regarding this issue.

The trouble with wayland is reproduced only when the saved panel size is a little bit less than the screen size. Otherwise you may not notice small increasing the panel size. See screenshots above.

**Comment by oleg68** [comment] 2023-01-07 19:52
@ministerinmarin The crescendo panel did not fit on the screen before you saved. That is why GrandOrgue shows it centered.

Try to move/resize it to fit in the screen area before saving.

**Closed** 2023-01-23 19:51 UTC

**Comment by rousseldenis** [comment] 2025-05-22 06:50
On Ubuntu 24, Wayland is the default, so, if you want to keep Wayland for your other applications, you can launch GrandOrgue with x11 specifically.

See: https://github.com/GrandOrgue/grandorgue/discussions/2102#discussioncomment-13229971
