### ISSUE TITLE
GO crashes immediately upon launch

### ISSUE THREAD

**Issue by ExBaker** [GrandOrgue/grandorgue#1811] opened 2024-02-22 17:05 UTC
Hello!

GO (v3.13.3-1) was working fine yesterday. Today it closes/crashes about one second after I launch it. No error, no dialogs, just the main window closing. FYI, no update to Windows 11 overnight. I'm running v22H2.

Through trial and error, I discovered that it will open if I turn off my audio interface (Audient id44 MK1) before launching. It opens and complains there is no audio output, as expected. I turn on my interface, select RTaudio and the ASIO driver and close the dialog. GO crashes again.

It doesn't exhibit this problem using Port Audio, but I can't play with that latency. I need to use ASIO. FYI, I'm using the latest version of my interface's driver.

I captured this from the Windows Event Viewer. It's definitely a crash in GO.

Faulting application name: GrandOrgue.exe, version: 3.13.3.0, time stamp: 0x00000000
Faulting module name: GrandOrgue.exe, version: 3.13.3.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000000000025b425
Faulting process id: 0x0xFF0
Faulting application start time: 0x0x1DA6460865D3EB9
Faulting application path: C:\Program Files\GrandOrgue\bin\GrandOrgue.exe
Faulting module path: C:\Program Files\GrandOrgue\bin\GrandOrgue.exe
Report Id: f87a0989-9aac-4dcc-b685-18ce519d43b1
Faulting package full name:
Faulting package-relative application ID:​

Any ideas why it doesn't seem to want to start?

TIA,
Tom

**Comment by Psi58** [comment] 2024-02-22 17:24
Sounds very similar to https://github.com/GrandOrgue/grandorgue/issues/1772. Caused by an issue in the latest ASIO SDK apparently.
Hopefully will be resolved in 3.14 (you could try the intermediate build shared in the issue in the meantime)

Best wishes,
Simon

**Comment by ExBaker** [comment] 2024-02-22 17:57
Thanks for the speedy response, Simon! I installed 3.12.3-1 and it resolved the issue. I look forward to the fix in 3.14!

In the meantime, I think you can mark #1811 a Duplicate of #1772.

Tom

**Comment by oleg68** [comment] 2024-02-22 19:23
@ExBaker could you try [this intermediate build](https://github.com/GrandOrgue/grandorgue/actions/runs/7971259824): whether it solves your problem?

**Comment by ExBaker** [comment] 2024-02-22 19:35
I installed v3.14.0-0.20 Windows x86_64 and i8t resolves the issue. I'm able to launch it without immediately closing. It launches, loads the last loaded organ, and allows me to play it using the ASIO driver and low latency settings I like.

Thanks so much!

Tom
________________________________

**Comment by oleg68** [comment] 2024-02-22 19:53
Duplicates #1772

**Closed** 2024-02-22 19:52 UTC
